version: '3'
services:
  redis-master:
    image: redis:5.0.1
    ports:
      - 6379:6379

  redis-slave:
    image: redis:5.0.1
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - 6380:6379

  redis-sentinel:
    build:
      context: ./
    image: lamoda/redis-sentinel:latest
    ports:
      - 26379:26379

  redis-sentinel2:
    image: lamoda/redis-sentinel:latest
    depends_on:
      - redis-sentinel
    ports:
      - 26380:26379

  redis-sentinel3:
    image: lamoda/redis-sentinel:latest
    depends_on:
      - redis-sentinel
    ports:
      - 26381:26379
