version: "3.0"
services:
  webserver:
    image: nginx
    volumes:
        - ./www:/var/www
        - ./conf/sites:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  php7.1:
    build:
      context: ./conf/php7.1
    volumes:
      - ./www:/var/www
    ports:
      - 9001:9000
  php7.2:
    build:
      context: ./conf/php7.2
    volumes:
      - ./www:/var/www
    ports:
      - 9002:9000
  dbredis:
    image: redis:5.0.1
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  dbmysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      #- ./data/mysql:/var/lib/mysql
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf